import { EvidenzLevel, KPIMeta, ScenarioMode, SliderInfo } from "./types";

export const SLIDER_INFO: Record<string, SliderInfo> = {
  beamte: {
    titel: "Anzahl Beamte",
    beschreibung: "Gesamtzahl der Beamtinnen und Beamten im Bundesdienst sowie in Landes- und Kommunaldiensten. Beamte sind unkündbar und erhalten Pensionen statt Renten.",
    aktuellerWert: "4.900.000",
    berechnungslogik: "Personalkosten = Anzahl × Ø-Jahresgehalt (58.400 €) + Versorgungsrückstellungen (23%). Einsparungen bei Reduzierung werden mit 3-jähriger Verzögerung wirksam.",
    annahmen: ["Ø-Jahresgehalt konstant bei 58.400 €", "Versorgungsquote 23% des Bruttogehalts", "Keine Neueinstellungen bei Reduzierung", "Natürliche Fluktuation 2,1% p.a."],
    quellen: [
      { name: "Statistisches Bundesamt", url: "https://destatis.de", aktualisiert: "Jan 2024" },
      { name: "Bundesministerium des Innern", url: "https://bmi.bund.de", aktualisiert: "Dez 2023" },
    ],
    evidenz: "hoch",
    evidenzHinweis: "Sehr gut belegte Kostenschätzungen, gestützt durch Destatis-Daten.",
  },
  ministerien: {
    titel: "Anzahl Bundesministerien",
    beschreibung: "Anzahl der Bundesministerien beeinflusst Verwaltungskosten, politische Koordinationsaufwände und bürokratischen Overhead.",
    aktuellerWert: "16",
    berechnungslogik: "Einsparung pro Ministerium: ~120 Mio. € (Personal, Gebäude, IT). Fusionskosten einmalig ~40 Mio. € pro Zusammenlegung.",
    annahmen: ["120 Mio. € Kostendurchschnitt pro Ministerium", "Einmalige Fusionskosten werden über 5 Jahre abgeschrieben"],
    quellen: [
      { name: "Bundeshaushalt.de", url: "https://bundeshaushalt.de", aktualisiert: "Feb 2024" },
    ],
    evidenz: "mittel",
    evidenzHinweis: "Schätzungen basieren auf historischen Fusionen; Effizienzgewinne sind unsicher.",
  },
  verteidigung: {
    titel: "Verteidigungsausgaben (% BIP)",
    beschreibung: "Anteil des Bruttoinlandsprodukts, der für die Bundeswehr und Verteidigungsinfrastruktur ausgegeben wird. NATO-Ziel liegt bei 2% BIP.",
    aktuellerWert: "2,0% BIP = 86,1 Mrd. €",
    berechnungslogik: "BIP Deutschland 2024: ~4,31 Bio. €. 1% BIP entspricht ~43,1 Mrd. €. Zusätzliche Ausgaben wirken sich direkt auf das Haushaltsdefizit aus.",
    annahmen: ["BIP 2024: 4,31 Bio. €", "Lineare Skalierung der Kosten", "Rüstungsindustrie-Multiplikator: 1,3 auf BIP"],
    quellen: [
      { name: "Bundesministerium der Verteidigung", url: "https://bmvg.de", aktualisiert: "Mär 2024" },
      { name: "NATO-Statistik", url: "https://nato.int", aktualisiert: "Feb 2024" },
    ],
    evidenz: "hoch",
    evidenzHinweis: "NATO-Berechnungsmethode ist standardisiert und international vergleichbar.",
  },
  entwicklung: {
    titel: "Entwicklungshilfe (% BIP)",
    beschreibung: "Deutsche Entwicklungszusammenarbeit (ODA). Das UN-Ziel liegt bei 0,7% BIP. Deutschland erfüllt es aktuell nicht vollständig.",
    aktuellerWert: "0,4% BIP = ca. 17 Mrd. €",
    berechnungslogik: "Direkte Haushaltswirkung: linearer Zusammenhang. Indirekte Effekte (Stabilität, Handelschancen) sind nicht modelliert.",
    annahmen: ["Lineare Haushaltswirkung", "Keine Modellierung indirekter Rückflüsse"],
    quellen: [
      { name: "BMZ – Bundesministerium für wirtschaftliche Zusammenarbeit", url: "https://bmz.de", aktualisiert: "Jan 2024" },
      { name: "OECD DAC", url: "https://oecd.org", aktualisiert: "Mär 2024" },
    ],
    evidenz: "hoch",
    evidenzHinweis: "Haushaltswirkung direkt ableitbar; Entwicklungseffekte unsicher.",
  },
  fluechtlinge: {
    titel: "Flüchtlingsaufnahme (pro Jahr)",
    beschreibung: "Anzahl der jährlich aufgenommenen Asylsuchenden. Beeinflusst Integrationskosten, Sozialausgaben, langfristig aber auch Fachkräfteangebot und BIP.",
    aktuellerWert: "180.000 / Jahr (2023)",
    berechnungslogik: "Kosten: ~18.000 € pro Person/Jahr (Unterbringung, Sozialleistungen, Verwaltung). Langfristig: 60% Erwerbsquote nach 5 Jahren, Steuereinnahmen berücksichtigt.",
    annahmen: ["18.000 € Kosten/Person/Jahr", "60% Erwerbsquote nach 5 Jahren", "Ø-Steuer/Sozialbeitrag nach Integration: 9.200 €/Jahr"],
    quellen: [
      { name: "Bundesamt für Migration und Flüchtlinge (BAMF)", url: "https://bamf.de", aktualisiert: "Mär 2024" },
      { name: "IAB-Forschungsbericht", url: "https://iab.de", aktualisiert: "Dez 2023" },
    ],
    evidenz: "mittel",
    evidenzHinweis: "Kurzfristkosten gut belegt; Langfristeffekte stark von Integrationspolitik abhängig.",
  },
  fachkraefte: {
    titel: "Fachkräftezuwanderung (pro Jahr)",
    beschreibung: "Gezielte Einwanderung qualifizierter Arbeitskräfte aus Nicht-EU-Ländern. Fachkräftemangel kostet Deutschland aktuell ~100 Mrd. € jährlich an entgangenem BIP-Wachstum.",
    aktuellerWert: "200.000 / Jahr (Ziel 2024)",
    berechnungslogik: "BIP-Effekt: +0,08% BIP pro 100k Fachkräfte. Steuereinnahmen: Ø 14.500 € pro qualifizierter Arbeitskraft/Jahr. Integrationskosten: ~8.000 € im ersten Jahr.",
    annahmen: ["Ø-Bruttolohn qualifiziert: 52.000 €/Jahr", "Sofortige Erwerbstätigkeit angenommen", "Fachkräftemangel-Gap: 890k Stellen"],
    quellen: [
      { name: "Bundesagentur für Arbeit", url: "https://arbeitsagentur.de", aktualisiert: "Feb 2024" },
      { name: "OECD Migration Outlook", url: "https://oecd.org", aktualisiert: "Jan 2024" },
    ],
    evidenz: "hoch",
    evidenzHinweis: "Starke empirische Basis durch IAB und OECD-Studien.",
  },
  buergergeld: {
    titel: "Bürgergeld (EUR/Monat)",
    beschreibung: "Grundsicherung für Arbeitsuchende. Ersetzt seit 2023 Hartz IV. Beeinflusst Arbeitsanreize, Armut und Staatsausgaben.",
    aktuellerWert: "502 EUR/Monat (Regelsatz 2024)",
    berechnungslogik: "Gesamtkosten: Empfänger × 12 × Regelsatz. Aktuell: 5,5 Mio. Empfänger. Arbeitsangebotseffekt: -0,3% pro 10% Erhöhung (IAB-Schätzung).",
    annahmen: ["5,5 Mio. Empfänger konstant", "Elastizität Arbeitsangebot: -0,3 pro 10% Erhöhung", "Keine Veränderung Vermittlungsquote"],
    quellen: [
      { name: "Bundesagentur für Arbeit", url: "https://arbeitsagentur.de", aktualisiert: "Jan 2024" },
      { name: "IAB – Institut für Arbeitsmarkt- und Berufsforschung", url: "https://iab.de", aktualisiert: "Feb 2024" },
    ],
    evidenz: "mittel",
    evidenzHinweis: "Arbeitsangebotseffekte sind wissenschaftlich umstritten; Schätzband ±50%.",
  },
  rentenalter: {
    titel: "Renteneintrittsalter",
    beschreibung: "Regelaltersgrenze für den Renteneintritt. Beeinflusst Fachkräfteangebot, Rentenkosten und Altersarmut. Derzeit schrittweise Anhebung auf 67.",
    aktuellerWert: "67 Jahre (Regelgrenze 2031)",
    berechnungslogik: "Pro Jahr Erhöhung: ~18,5 Mrd. € weniger Rentenausgaben. Gleichzeitig +200k Erwerbspersonen im Markt, BIP +0,3%.",
    annahmen: ["18,5 Mrd. € Einsparung pro Jahr Anhebung", "Keine Erhöhung der Erwerbsminderungsrenten eingerechnet", "Gesundheitliche Arbeitsfähigkeit bis 70 angenommen"],
    quellen: [
      { name: "Deutsche Rentenversicherung Bund", url: "https://drv-bund.de", aktualisiert: "Mär 2024" },
      { name: "Sachverständigenrat Wirtschaft", url: "https://sachverstaendigenrat-wirtschaft.de", aktualisiert: "Nov 2023" },
    ],
    evidenz: "hoch",
    evidenzHinweis: "Fiskalische Effekte sehr gut modelliert; soziale Verteilungswirkung kontrovers.",
  },
  euZuwanderung: {
    titel: "EU-Freizügigkeit",
    beschreibung: "Die EU-Freizügigkeit (Art. 45 AEUV) ermöglicht ca. 4,5 Mio. EU-Bürger:innen das Arbeiten in Deutschland. Sie ist ein Grundprinzip des EU-Binnenmarkts und kann von Deutschland nicht einseitig aufgekündigt werden. Das Modell simuliert ein hypothetisches Szenario, um wirtschaftliche Abhängigkeiten zu veranschaulichen.",
    aktuellerWert: "Aktiv (EU-Vertrag Art. 45 AEUV)",
    berechnungslogik: "Bei Abschaffung: ca. −10 Mrd. € Steuer- und Beitragseinnahmen (Ø 10.200 € je EU-Arbeitnehmer × 4,5 Mio.), −0,35 % BIP-Wachstum, +180k offene Fachkraftstellen. Handelswirkungen nicht modelliert.",
    annahmen: [
      "4,5 Mio. EU-Arbeitnehmer in Deutschland",
      "Ø Steuern und Sozialbeiträge: 10.200 €/Jahr",
      "Sofortiger vollständiger Effekt angenommen",
      "Keine Modellierung von Handelsumlenkungen",
    ],
    quellen: [
      { name: "Institut für Arbeitsmarkt- und Berufsforschung (IAB)", url: "https://iab.de", aktualisiert: "Jan 2024" },
      { name: "Eurostat – Arbeitsmigration EU", url: "https://ec.europa.eu/eurostat", aktualisiert: "Feb 2024" },
    ],
    evidenz: "mittel" as EvidenzLevel,
    evidenzHinweis: "Grundeffekte durch IAB-Daten gut belegt; langfristige Verhaltens- und Handelsanpassungen unsicher.",
  },
  einkommensteuer: {
    titel: "Einkommensteuer Spitzensatz",
    beschreibung: "Gilt ab einem zu versteuernden Einkommen von 66.761 €/Jahr. Beeinflusst Steueraufkommen, Leistungsanreize und Einkommensverteilung.",
    aktuellerWert: "42% (+ 5,5% Solidaritätszuschlag für Spitzenverdiener)",
    berechnungslogik: "Steueraufkommen-Änderung: ca. 3,2 Mrd. € pro Prozentpunkt. Verhaltensanpassung (Laffer-Effekt) ab ~50% eingerechnet: Elastizität −0,2.",
    annahmen: ["3,2 Mrd. EUR je Prozentpunkt", "Elastizität steuerpflichtiges Einkommen: −0,2", "Laffer-Kurven-Effekt ab 50% modelliert"],
    quellen: [
      { name: "Bundesministerium der Finanzen", url: "https://bundesfinanzministerium.de", aktualisiert: "Feb 2024" },
      { name: "IW Köln – Steuerreportstudie", url: "https://iwkoeln.de", aktualisiert: "Jan 2024" },
    ],
    evidenz: "mittel",
    evidenzHinweis: "Kurzfristeffekte gut belegt; Verhaltensanpassungen langfristig unsicher.",
  },
  vmFreibetrag: {
    titel: "Vermögensteuer – Freibetrag",
    beschreibung: "Ab welchem Nettovermögen die Steuer greift. Höherer Freibetrag schützt kleinere Vermögen und reduziert die Zahl der Steuerpflichtigen erheblich. Der Großteil des deutschen Privatvermögens (ca. 15,1 Bio. €) konzentriert sich auf die obersten Dezile.",
    aktuellerWert: "Nicht existent (keine Vermögensteuer in Deutschland seit 1997)",
    berechnungslogik: "Modell: 1 Mio. € Freibetrag ≈ 1,4× Basisertrag, 2 Mio. ≈ 1,0×, 5 Mio. ≈ 0,6×, 10 Mio. ≈ 0,38×, 20 Mio. ≈ 0,22× (exponentielle Vermögenskonzentration lt. DZW). Basisertrag 8 Mrd. bei 1% / 2 Mio.-Freibetrag vor Kapitalfluchtanpassung.",
    annahmen: ["Nettovermögensbasis: 15,1 Bio. € (Bundesbank 2023)", "Exponentiell sinkende Steuerpflichtigenanzahl je Freibetrags-Tier", "Keine Modellierung von Bewertungsstreitigkeiten"],
    quellen: [
      { name: "Deutsche Bundesbank – Vermögensverteilung", url: "https://bundesbank.de", aktualisiert: "Nov 2023" },
      { name: "DIW Berlin – PHF-Studie", url: "https://diw.de", aktualisiert: "Dez 2023" },
    ],
    evidenz: "gering" as EvidenzLevel,
    evidenzHinweis: "Vermögenserfassung und Kapitalfluchteffekte stark unsicher; keine aktuelle Bemessungsgrundlage.",
  },
  vmRate: {
    titel: "Vermögensteuer – Steuersatz",
    beschreibung: "Jährlich erhobener Prozentsatz auf das steuerpflichtige Nettovermögen. Höhere Sätze erhöhen theoretisch das Aufkommen, steigern aber auch Kapitalflucht und Verwaltungsaufwand. Frankreichs ISF zeigte bei 1,5 % bereits erhebliche Ausweichreaktionen; die Schweiz erhebt 0,3–0,5 % erfolgreich.",
    aktuellerWert: "0 % (nicht existent)",
    berechnungslogik: "0,5 % → Faktor 0,50; 1,0 % → 1,0; 1,5 % → 1,35; 2,0 % → 1,6; 3,0 % → 1,8 (Laffer-Dämpfung bei höheren Sätzen). Kapitalfluchtrisiko steigt exponentiell ab ca. 1,5 %.",
    annahmen: ["Laffer-Dämpfung ab 1,5 % modelliert", "Kapitalfluchtelastizität: −0,3 per Prozentpunkt über 1 %", "Schweizer Erfahrung als untere Schranke"],
    quellen: [
      { name: "OECD – Wealth Taxes", url: "https://oecd.org", aktualisiert: "Jan 2024" },
      { name: "IW Köln – Vermögensteuer-Gutachten", url: "https://iwkoeln.de", aktualisiert: "Feb 2024" },
    ],
    evidenz: "gering" as EvidenzLevel,
    evidenzHinweis: "Internationale Erfahrungen zeigen stark divergierende Aufkommenswirkungen; Kapitalflucht schwer quantifizierbar.",
  },
  vmBetrieb: {
    titel: "Vermögensteuer – Betriebsvermögen",
    beschreibung: "Betriebsvermögen macht einen Großteil des steuerbaren Privatvermögens aus. Die Besteuerung birgt das Risiko von Liquiditätsproblemen bei KMU und Familienunternehmen. Vollständige Besteuerung maximiert Aufkommen, erhöht aber Substanzsteuer-Risiko.",
    aktuellerWert: "Keine Regelung (Vermögensteuer nicht existent)",
    berechnungslogik: "Voll steuerpflichtig: Faktor 1,0; 50 % steuerpflichtig: 0,75; Befreit: 0,50 auf die berechnete Steuerbasis (Restbasis durch Privatvermögen bleibt).",
    annahmen: ["Betriebsvermögen ca. 40 % des steuerbaren Gesamtvermögens", "Keine Modellierung von Bewertungsfragen Betrieb (Sachwertmethode vs. Ertragswert)"],
    quellen: [
      { name: "Bundesministerium der Finanzen – Erbschaftsteuer-Statistik", url: "https://bundesfinanzministerium.de", aktualisiert: "Jan 2024" },
      { name: "Sachverständigenrat Wirtschaft", url: "https://sachverstaendigenrat-wirtschaft.de", aktualisiert: "Nov 2023" },
    ],
    evidenz: "gering" as EvidenzLevel,
    evidenzHinweis: "Bewertung von Betriebsvermögen ist hochkomplex und stark rechtlich geprägt; Modellwirkung vereinfacht.",
  },
  estSpitzenbeginn: {
    titel: "Einkommensteuer – Beginn Spitzensteuersatz",
    beschreibung: "Ab welchem Jahreseinkommen der Spitzensteuersatz von 42 % greift. Derzeit gilt er ab 66.761 €. Eine Anhebung entlastet Einkommensmittelschicht, reduziert aber Steueraufkommen. Wichtig: ca. 3 % der Steuerpflichtigen zahlen heute den Spitzensteuersatz und tragen ~25 % des ESt-Aufkommens.",
    aktuellerWert: "66.761 €/Jahr (2024), im Modell als 80.000 € vereinfacht",
    berechnungslogik: "Jede Anhebung um 10.000 € entlastet ca. 120.000 Steuerpflichtige. Minderjahressteuer-Verlust: Ø 3.000 €/Person/Jahr → ca. 0,36 Mrd. je 10.000 € Anhebung.",
    annahmen: ["120.000 Steuerpflichtige pro 10.000 € Schwellenanhebung", "Ø Entlastung 3.000 €/Person/Jahr", "Keine Zweitrundeneffekte modelliert"],
    quellen: [
      { name: "Bundesministerium der Finanzen – Datensammlung Steuerpolitik", url: "https://bundesfinanzministerium.de", aktualisiert: "Feb 2024" },
      { name: "IW Köln – ESt-Aufkommensstruktur", url: "https://iwkoeln.de", aktualisiert: "Dez 2023" },
    ],
    evidenz: "mittel" as EvidenzLevel,
    evidenzHinweis: "Kurzfristeffekte gut belegt; Verhaltensänderungen (Mehrarbeit) langfristig unsicher.",
  },
  reichensteuer: {
    titel: "Reichensteuer",
    beschreibung: "Ein neuer Steuersatz für sehr hohe Einkommen, zusätzlich zur bestehenden Spitzensteuerpflicht (derzeit 45 % ab 277.825 €). Befürworter sehen Finanzierungsspielraum, Kritiker warnen vor Abwanderung von Spitzenverdienern. Frankreichs 'supertaxe' (75 %) zeigte erhebliche Emigrationseffekte und wurde abgeschafft.",
    aktuellerWert: "De facto: 45 % 'Reichensteuer' bereits ab 277.825 € (inkl. Soli). Modell: zusätzlicher Satz darüber.",
    berechnungslogik: "Zusatzertrag: 3 Mrd. Basispotenzial (250k-Schwelle, 50 %) × Schwellenfaktor × Ratenüberschuss / 5 × Szenarien-Dämpfung. Emigrationsrisiko: −0,4 Mrd. pro Prozentpunkt ab 55 %.",
    annahmen: ["Basispotenzial 3 Mrd. EUR (IZA-Schätzung für neue Spitzenklasse)", "Emigrationselastizität −0,4 Mrd./pp ab 55 %", "Verhaltensanpassung (Steuervermeidung) nicht vollständig modelliert"],
    quellen: [
      { name: "IZA – Spitzeneinkommensteuer und Abwanderung", url: "https://iza.org", aktualisiert: "Jan 2024" },
      { name: "DIW Berlin – Reichensteuer-Simulationen", url: "https://diw.de", aktualisiert: "Nov 2023" },
    ],
    evidenz: "gering" as EvidenzLevel,
    evidenzHinweis: "Verhaltensreaktionen (Emigration, Steuervermeidung) sehr schwer modellierbar; historische Erfahrungen stark kontextabhängig.",
  },
  schuldenbremse: {
    titel: "Schuldenbremse",
    beschreibung: "Verfassungsrechtliche Fiskalregel (Art. 109/115 GG), in Kraft seit 2011. Begrenzt das strukturelle Defizit des Bundes auf 0,35 % BIP (~15 Mrd. €). Eine Reform würde mehr staatliche Investitionen ermöglichen, erhöht aber Schuldenlast und Zinskosten. Reformiert = Investitionsausnahme für Bildung/Infrastruktur.",
    aktuellerWert: "Aktiv (strukturelles Defizitlimit 0,35 % BIP = ~15 Mrd. €/Jahr)",
    berechnungslogik: "Alle Beträge sind Modellschätzungen auf Basis von IWF-Fiskalmultiplikatoren und Bundeshaushalts-Analysen — keine offiziell festgelegten Werte. Reformiert: +20 Mrd. Investitionskredit (netto nach Zinsen: +18 Mrd.), Wachstumsmultiplikator 1,2. Ausgesetzt: +50 Mrd. Brutto-Spielraum (+44 Mrd. netto). Abgeschafft: +80 Mrd. Brutto (+66 Mrd. netto). Zinsmehrkosten: +0,1–0,4 % Risikoprämie auf 2.445 Mrd. Schulden.",
    annahmen: ["⚠ Modellannahme: Ausgabenspielräume sind Näherungswerte, keine politisch beschlossenen Beträge", "Fiskalmultiplikator Investitionen: 1,2 (IWF-Schätzung für Deutschland)", "Risikoprämien-Anstieg: +0,08 % (reformiert) bis +0,5 % (abgeschafft)", "Keine Modellierung von EU-Fiskalregeln (Stabilitätspakt)"],
    quellen: [
      { name: "Sachverständigenrat – Jahresgutachten 2023", url: "https://sachverstaendigenrat-wirtschaft.de", aktualisiert: "Nov 2023" },
      { name: "IMF – Fiscal Multipliers Germany", url: "https://imf.org", aktualisiert: "Jan 2024" },
      { name: "IWH Halle – Schuldenbremsen-Reform", url: "https://iwh-halle.de", aktualisiert: "Feb 2024" },
    ],
    evidenz: "mittel" as EvidenzLevel,
    evidenzHinweis: "Fiskalmultiplikatoren in der Forschung umstritten (0,5–1,5); Zinseffekte von Rating-Reaktion abhängig.",
  },
  co2Preis: {
    titel: "CO₂-Preis",
    beschreibung: "Preis für CO₂-Emissionsrechte im EU-ETS und nationalen Brennstoffemissionshandel (nBEHS). Höhere Preise senken Emissionen, erhöhen Energiekosten und generieren Staatseinnahmen. Aktuelle Preise: ETS ~60–65 €/t (2024), nBEHS 45 €/t (Festpreis bis Ende 2025).",
    aktuellerWert: "ETS: ~62 €/t (Feb 2024), nBEHS: 45 €/t (Festpreis)",
    berechnungslogik: "Einnahmen: ΔPreis × 180 Mio. Zertifikate ≈ 180 Mio. € je €/t. Emissionen: −1,8 Mt CO₂ je €/t (gemittelte Preiselastizität). Strompreis: +0,02 ct/kWh je €/t (Merit-Order-Effekt).",
    annahmen: ["180 Mio. handelbare Zertifikate im deutschen Markt", "Preiselastizität CO₂: −1,8 Mt/€ (Ø aus Fraunhofer ISE)", "Vollständige Weitergabe an Endkunden angenommen"],
    quellen: [
      { name: "Umweltbundesamt – Emissionshandel", url: "https://umweltbundesamt.de", aktualisiert: "Mär 2024" },
      { name: "Fraunhofer ISE – CO₂-Preis-Modell", url: "https://ise.fraunhofer.de", aktualisiert: "Jan 2024" },
      { name: "Sachverständigenrat Klimaschutz", url: "https://expertenrat-klima.de", aktualisiert: "Feb 2024" },
    ],
    evidenz: "hoch" as EvidenzLevel,
    evidenzHinweis: "Einnahmen und kurzfristige Emissionseffekte gut empirisch belegt; langfristige Elastizitäten unsicher.",
  },
  windausbau: {
    titel: "Windkraftausbau",
    beschreibung: "Ausbaupace der Windenergie (an Land + Offshore) relativ zum aktuellen Tempo (~8–10 GW/Jahr). 100 % = Baseline = aktuelles Ausbautempo (Ist-Zustand). Erhöhter Ausbau senkt langfristig Strompreise durch niedrige Grenzkosten, erfordert aber Netzausbau und Systemintegration.",
    aktuellerWert: "Baseline (100 %): ~8–10 GW Neuinstallation/Jahr (Ist-Zustand 2023/24). Referenzwert (nicht Baseline): Regierungsziel 115 GW Onshore + 30 GW Offshore bis 2030.",
    berechnungslogik: "Alle Deltas beziehen sich auf die Baseline = aktuelles Ausbautempo (100 %). +1 % über Status quo → −0,025 ct/kWh Strompreis (Merit-Order), −0,8 Mt CO₂. Subventionen: +0,12 Mrd. je 10 % über Status quo (EEG-Umlage-Äquivalent). Unter 100 %: Umkehreffekte.",
    annahmen: ["Merit-Order-Modell: neue kWh verdrängt fossile Spitzenlast", "Netzausbaukosten nicht vollständig modelliert", "Systemintegration (Speicher) ab 150 % zusätzliche Kosten"],
    quellen: [
      { name: "Bundesnetzagentur – Monitoringbericht", url: "https://bundesnetzagentur.de", aktualisiert: "Feb 2024" },
      { name: "Fraunhofer ISE – Energy Charts", url: "https://energy-charts.info", aktualisiert: "Mär 2024" },
    ],
    evidenz: "mittel" as EvidenzLevel,
    evidenzHinweis: "Merit-Order-Effekte gut modelliert; Systemintegrations- und Netzausbaukosten schwer zu pauschalisieren.",
  },
  solarausbau: {
    titel: "Solarausbau",
    beschreibung: "Ausbaupace der Photovoltaik relativ zum aktuellen Tempo (~14–15 GW/Jahr). 100 % = Baseline = aktuelles Ausbautempo (Ist-Zustand). Solarstrom hat nahezu null Grenzkosten und senkt mittags die Börsenstrompreise. Herausforderung: Volatilität und Speicherbedarf.",
    aktuellerWert: "Baseline (100 %): ~14–15 GW Neuinstallation/Jahr (Ist-Zustand 2023/24). Referenzwert (nicht Baseline): Regierungsziel 215 GW kumuliert bis 2030.",
    berechnungslogik: "Alle Deltas beziehen sich auf die Baseline = aktuelles Ausbautempo (100 %). +1 % über Status quo → −0,010 ct/kWh Strompreis (Merit-Order mittags), −0,3 Mt CO₂. Subventionen: +0,06 Mrd. je 10 % (EEG-Differenzkosten bei Spot-Minus).",
    annahmen: ["Grenzkosten Solar: 0 €/kWh", "Subventionen: Differenz zwischen EEG-Vergütung und Börsenpreis", "Duck Curve Effekte ab 150 % erhöhen Systemkosten"],
    quellen: [
      { name: "Fraunhofer ISE – Photovoltaics Report", url: "https://ise.fraunhofer.de", aktualisiert: "Feb 2024" },
      { name: "Bundesnetzagentur – EEG-Statistik", url: "https://bundesnetzagentur.de", aktualisiert: "Jan 2024" },
    ],
    evidenz: "mittel" as EvidenzLevel,
    evidenzHinweis: "Kurzfristige Merit-Order-Effekte gut modelliert; Systemkosten bei hohen Anteilen stark modellannahmenabhängig.",
  },
  atomkraft: {
    titel: "Atomkraft",
    beschreibung: "Deutschland hat alle verbliebenen AKW im April 2023 abgeschaltet. Eine Laufzeitverlängerung wäre technisch sehr aufwendig (neue Sicherheitsprüfungen, Brennstoffbeschaffung). Neubau würde 15–25 Jahre dauern und 10–25 Mrd. € pro Reaktor kosten. Dies ist ein hypothetisches Szenario.",
    aktuellerWert: "Alle AKW abgeschaltet (April 2023)",
    berechnungslogik: "Laufzeitverlängerung: −2 ct/kWh Strompreis, −20 Mt CO₂, −1 Mrd. Betriebssubventionen. Neubau: −4 ct/kWh (langfristig), −50 Mt CO₂, +15 Mrd. Baukosten (kurzfristig). Alle Effekte als einheitlich angenommen – in der Realität stark projektspezifisch.",
    annahmen: ["Laufzeitverlängerung: 3 Reaktoren à ~1,4 GW reaktivierbar", "Neubau: 2 Druckwasserreaktoren, je 15 Mrd. Bauzeit 20 Jahre", "Betriebskosten Kernkraft: 5–7 ct/kWh"],
    quellen: [
      { name: "Fraunhofer ISE – Kernenergie-Analyse", url: "https://ise.fraunhofer.de", aktualisiert: "Mär 2024" },
      { name: "IAEA – Cost of Nuclear Electricity", url: "https://iaea.org", aktualisiert: "Feb 2024" },
      { name: "Bundeministerium für Wirtschaft und Klimaschutz", url: "https://bmwk.de", aktualisiert: "Jan 2024" },
    ],
    evidenz: "gering" as EvidenzLevel,
    evidenzHinweis: "Kostenschätzungen für Reaktivierung/Neubau extrem unsicher; internationaler Vergleich zeigt Bandbreite 5× bis 10×.",
  },
  kohleausstieg: {
    titel: "Kohleausstiegsdatum",
    beschreibung: "Gesetzlicher Kohleausstieg spätestens 2038 (Kohleausstiegsgesetz 2020). Politisches Ziel ist ein möglichst vorgezogener Ausstieg bis 2030. Das Modell verwendet 2030 als Nulllinie (Baseline), da dies dem aktuellen Regierungsziel entspricht. Abweichungen nach hinten bedeuten im Modell eine Verzögerung gegenüber dem politischen Ziel.",
    aktuellerWert: "Rechtslage: Kohleausstieg spätestens 2038 (§ 4 KVBG). Politisches Ziel: Vorziehung auf 2030 (Koalitionsvertrag 2021). Modell-Baseline: 2030.",
    berechnungslogik: "Modell-Baseline = 2030 (Regierungsziel). Alle Deltas beziehen sich auf diesen Ausgangspunkt. Jedes spätere Datum: kurzfristig günstigerer Strom durch weiter laufende Kohlekraft (+0,7–1,5 ct/kWh), aber mehr CO₂ (+20–70 Mt gegenüber 2030-Szenario). Entschädigungen für Kraftwerksbetreiber (rd. 4,35 Mrd. €, vereinbart 2021) sind im Modell nicht als variable Ausgabe erfasst.",
    annahmen: ["⚠ Modell-Baseline ist 2030 (politisches Ziel), NICHT der Rechtsstatus 2038", "Entschädigungen bereits verhandelt — werden nicht als variable Modellasgabe erfasst", "CO₂-Delta pro Jahr verzögerter Ausstieg gegenüber 2030: ca. 20–25 Mt"],
    quellen: [
      { name: "Umweltbundesamt – THG-Emissionen", url: "https://umweltbundesamt.de", aktualisiert: "Mär 2024" },
      { name: "Fraunhofer ISE – Kohleausstieg-Studien", url: "https://ise.fraunhofer.de", aktualisiert: "Jan 2024" },
    ],
    evidenz: "hoch" as EvidenzLevel,
    evidenzHinweis: "Emissionseffekte gut dokumentiert; Strompreiseffekte abhängig von Ersatzerzeugung.",
  },
  sozialwohnungen: {
    titel: "Sozialwohnungsbau (pro Jahr)",
    beschreibung: "Staatlich geförderte Mietwohnungen mit Belegungsbindung und Mietpreisbindung. Deutschland baut derzeit ~30.000 Sozialwohnungen/Jahr, während jährlich ~50.000 aus der Bindung fallen. Netto schrumpft der Bestand. Ziel der Regierung: 100.000/Jahr.",
    aktuellerWert: "~30.000 Einheiten/Jahr (Bundesregierung 2023); Bindungsauslauf ~50.000/Jahr",
    berechnungslogik: "Bundesförderanteil: ~40–50k € pro Wohneinheit. Hinweis: Dies ist ausschließlich der Bundesförderanteil (Zuschuss/Darlehen), NICHT die Gesamtbaukosten (~250–400k € je nach Region und Ausstattung). Grundstücks- und Länderanteile sind nicht enthalten. Mietniveau-Effekt: je 10.000 Einheiten über Status quo → −0,15 Indexpunkte. Wohnraumdefizit-Abbau: 1 gebaut = 1,5 weniger Mangel (Multiplier durch Flächenmobilisierung).",
    annahmen: ["Bundesförderanteil pro Einheit: 45.000 € (Bundesschnitt, Quelle: BMWSB)", "⚠ Gesamtbaukosten (~250–400k €) werden nicht im Modell erfasst (Länder- und Eigenanteile)", "Keine Grundstückskosten im Modell (Länder-Aufgabe)", "Jährlicher Nettoneubau = Bau minus Bindungsauslauf"],
    quellen: [
      { name: "Bundesministerium für Wohnen, Stadtentwicklung und Bauwesen", url: "https://bmwsb.bund.de", aktualisiert: "Feb 2024" },
      { name: "Institut Pestel – Wohnraum-Gutachten", url: "https://pestel-institut.de", aktualisiert: "Jan 2024" },
    ],
    evidenz: "mittel" as EvidenzLevel,
    evidenzHinweis: "Kostenansätze gut belegt; Mietpreiseffekte im Gesamtmarkt schwer isolierbar.",
  },
  mietpreisbremse: {
    titel: "Mietpreisbremse",
    beschreibung: "Begrenzung von Wiedervermietungsmieten auf Mietspiegel + 10 %. Seit 2015 in Kraft, durch Ausnahmen und Vollzugsdefizite in der Wirkung begrenzt. Bundesverfassungsgericht hat den Berliner Mietendeckel 2021 gekippt. Kurzfristig entlastet Mieter, langfristig kann es Neubau und Sanierung hemmen.",
    aktuellerWert: "Aktiv in ca. 650 Gemeinden mit angespanntem Wohnungsmarkt",
    berechnungslogik: "Mietniveaueffekt: −5 Indexpunkte (kurzfristig). Investitionsrückgang: −0,5 Mrd. € private Wohnungsbauinvestitionen. Wohnraumdefizit: +20k Einheiten langfristig (durch geringere Neubauanreize).",
    annahmen: ["Mietniveaueffekt basiert auf DIW-Untersuchung Berlin 2019–2020", "Investitionsrückgang: IW-Köln-Schätzung", "Keine Vollzugsdefizite modelliert"],
    quellen: [
      { name: "DIW Berlin – Mietendeckel Wirkungsanalyse", url: "https://diw.de", aktualisiert: "Dez 2023" },
      { name: "IW Köln – Mietpreisbremse und Wohnungsbau", url: "https://iwkoeln.de", aktualisiert: "Jan 2024" },
    ],
    evidenz: "gering" as EvidenzLevel,
    evidenzHinweis: "Kurzfristeffekte in Studien gut dokumentiert; Langfristeffekte auf Wohnungsmarkt stark umstritten.",
  },
  wohngeld: {
    titel: "Wohngeld (Erhöhung)",
    beschreibung: "Staatlicher Mietzuschuss für einkommensschwache Haushalte. 2023 stark ausgeweitet (Wohngeldplus: ~700.000 Haushalte neu berechtigt). Eine weitere Erhöhung entlastet Mieter direkt, kann aber indirekt Mieten erhöhen (höhere Zahlungsbereitschaft). Direkte Staatsausgabe: ca. 5 Mrd. €/Jahr (2024).",
    aktuellerWert: "~5 Mrd. € Gesamtausgaben (2024, nach Wohngeldplus-Reform)",
    berechnungslogik: "Jede 1 % Erhöhung = +0,05 Mrd. € Ausgaben. Keine Gegenfinanzierung angenommen. Mieteffekt: neutralisiert partweise den direkten Mietniveaueffekt (+0,5 Indexpunkte je 10% Wohngelderhöhung).",
    annahmen: ["5 Mrd. € Ausgabenbasis 2024", "Keine Verhaltensänderung der Vermieter modelliert", "1 % Erhöhung ≈ 50 Mio. € Mehrausgaben"],
    quellen: [
      { name: "BMWSB – Wohngeld-Statistik", url: "https://bmwsb.bund.de", aktualisiert: "Feb 2024" },
      { name: "Bundesrechnungshof – Wohngeld Evaluation", url: "https://bundesrechnungshof.de", aktualisiert: "Jan 2024" },
    ],
    evidenz: "mittel" as EvidenzLevel,
    evidenzHinweis: "Ausgabeneffekte direkt modellierbar; Wirkung auf Mietniveau empirisch umstritten.",
  },
  bildungsausgaben: {
    titel: "Bildungsausgaben (% BIP)",
    beschreibung: "Öffentliche Ausgaben für Kita, Schulen, Hochschulen und Weiterbildung. Deutschland gibt ca. 4,3 % BIP aus (OECD-Schnitt ~5,5 %). Mehrinvestitionen wirken mit 5–10 Jahren Verzögerung auf Fachkräfteangebot und Produktivität. Wirkung modelliert als mittelfristig (5-Jahres-Horizont).",
    aktuellerWert: "~4,3 % BIP = ca. 185 Mrd. € (2023, Destatis)",
    berechnungslogik: "1 % BIP = 43,1 Mrd. € Mehrausgaben. Langfristiger Wachstumseffekt: +0,015 % BIP-Wachstum je 1 % Bildungsausgaben-Erhöhung (OECD-Meta-Analyse, 5-Jahres-Lag). Fachkräftelücke: −60k Stellen je 1 % mehr Bildungsausgaben (10-Jahres-Horizont).",
    annahmen: ["OECD-Bildungsmultiplikator: +0,015 %/% (5 Jahre)", "Fachkräfteeffekt: 10-Jahres-Horizont, hier als mittelfristig angezeigt", "Ausgaben umfassen alle Bildungsebenen"],
    quellen: [
      { name: "Statistisches Bundesamt – Bildungsausgaben", url: "https://destatis.de", aktualisiert: "Feb 2024" },
      { name: "OECD – Education at a Glance 2023", url: "https://oecd.org", aktualisiert: "Sep 2023" },
      { name: "IZA – Bildungsrenditen Metastudie", url: "https://iza.org", aktualisiert: "Jan 2024" },
    ],
    evidenz: "mittel" as EvidenzLevel,
    evidenzHinweis: "Kurzfristkosten sicher; Wachstumseffekte mit erheblicher Zeitverzögerung und Unsicherheit.",
  },
  kitaAusbau: {
    titel: "Kita-Ausbau (Erhöhung)",
    beschreibung: "Ausbau der Kinderbetreuung für unter 3-Jährige. Aktuelle Betreuungsquote: ~65 % (U3), erhebliche regionale Unterschiede. Bessere Betreuung erhöht die Frauenerwerbsquote, verbessert frühkindliche Bildungschancen und reduziert langfristig Fachkräftemangel. Slider 0–100 %: 100 % entspricht dem vollständigen Schließen der Versorgungslücke (aktuelle Quote ~65 % → ~100 % U3-Versorgung, ca. +35 Prozentpunkte), was im Modell ca. +13 Mrd. € Bundesausgaben entspricht.",
    aktuellerWert: "~65 % Betreuungsquote U3; ~95 % U6; Gesamtausgaben Bund ~5 Mrd. €/Jahr",
    berechnungslogik: "Slider-Wert 0 = Status quo (keine Änderung). Slider-Wert 100 = Vollausbau zur Schließung der U3-Versorgungslücke (~35 Prozentpunkte) ≈ +13 Mrd. € zusätzliche Bundesausgaben. Pro 1 Slider-Einheit: +0,13 Mrd. € und ca. +350 neue Betreuungsplätze. ALQ-Effekt: −0,1 pp Arbeitslosigkeit je 10 Slider-Einheiten durch höhere Frauenerwerbstätigkeit. Langfristiger Produktivitätseffekt: modelliert als Teilkomponente Bildungswachstum.",
    annahmen: ["5 Mrd. € Bundesausgaben als Basis (Ist-Zustand)", "100 % Slider = Schließung der U3-Lücke (~35 pp), nicht 100 % mehr Ausgaben", "+1 Slider-Einheit = ca. 350 neue U3-Plätze (Bundesschnitt)", "Frauenerwerbsquote-Elastizität: −0,01 pp ALQ je 10 Slider-Einheiten (DIW-Schätzung)"],
    quellen: [
      { name: "BMFSFJ – KiTa-Statistik", url: "https://bmfsfj.de", aktualisiert: "Jan 2024" },
      { name: "DIW Berlin – Erwerbstätigkeit und Kita", url: "https://diw.de", aktualisiert: "Dez 2023" },
    ],
    evidenz: "mittel" as EvidenzLevel,
    evidenzHinweis: "Ausgabeneffekte gut quantifizierbar; Erwerbseffekte mittel bis gut belegt; langfristige Bildungsrenditen unsicher.",
  },
  bafoeg: {
    titel: "BAföG (Erhöhung)",
    beschreibung: "Bundesausbildungsförderungsgesetz: staatliche Studienförderung. Aktuell: max. 992 €/Monat (2024), ~620.000 Geförderte, Gesamtausgaben ~3 Mrd. €/Jahr. Kritik: Einkommensgrenzen zu niedrig, Anteil geförderter Studierender zuletzt gesunken (von 25 % auf ~11 %).",
    aktuellerWert: "Max. 992 €/Monat (2024); ~3 Mrd. €/Jahr Gesamtausgaben",
    berechnungslogik: "+1 % Erhöhung der Sätze oder Ausweitung der Einkommensgrenzen: ca. +0,03 Mrd. Mehrausgaben. Langfristiger Wachstumseffekt: minimal (+0,003 % BIP-Wachstum je 50 % BAföG-Erhöhung).",
    annahmen: ["3 Mrd. € Basis-Ausgabenvolumen", "Kein Kosteneffizienzverlust bei Ausweitung modelliert", "Hochschulabsolventenquote bleibt konstant"],
    quellen: [
      { name: "Bundesministerium für Bildung und Forschung – BAföG-Statistik", url: "https://bmbf.de", aktualisiert: "Mär 2024" },
      { name: "Deutsches Studentenwerk", url: "https://studentenwerke.de", aktualisiert: "Feb 2024" },
    ],
    evidenz: "mittel" as EvidenzLevel,
    evidenzHinweis: "Ausgabeneffekt direkt modellierbar; Wachstums- und Bildungseffekte langfristig und schwer isolierbar.",
  },
  privatAbschaffen: {
    titel: "Private Krankenversicherung abschaffen",
    beschreibung: "Abschaffung der privaten Krankenversicherung (PKV) und vollständige Integration aller Versicherten in die gesetzliche Krankenversicherung (GKV). Rund 8,7 Mio. Menschen sind derzeit privat versichert, darunter Beamte und Selbstständige. Eine Abschaffung hätte massive Auswirkungen auf die Finanzierung des Gesundheitssystems und die Versorgungsstruktur.",
    aktuellerWert: "Dual: ~74 Mio. GKV + ~8,7 Mio. PKV-Versicherte",
    berechnungslogik: "Modell: Mehreinnahmen durch PKV-Beitragszahler (+7 Mrd. €), jedoch Mehrkosten durch erhöhte Inanspruchnahme und wegfallende PKV-Quersubventionierung von Ärzten (+11 Mrd. € Mehrausgaben). Netto im Modell: −4 Mrd. € (Nettobelastung). Langfristige Effekte auf Versorgungsstruktur nicht modelliert.",
    annahmen: [
      "~8,7 Mio. PKV-Versicherte wechseln in die GKV",
      "Ø PKV-Beitrag ~500 €/Monat → GKV ~350 €/Monat (Mehreinnahmen ~7 Mrd. €)",
      "Wegfall PKV-Quersubventionierung: Ärztehonorare steigen (Mehrausgaben ~11 Mrd. €)",
      "Beamte erhalten weiterhin Beihilfe (komplexe Übergangslösung nicht modelliert)",
      "Qualitätseffekte und Kapazitätsengpässe nicht quantifiziert",
    ],
    quellen: [
      { name: "Bundesministerium für Gesundheit – PKV-Statistik", url: "https://bundesgesundheitsministerium.de", aktualisiert: "Jan 2024" },
      { name: "PKV-Verband – Rechenschaftsbericht", url: "https://pkv.de", aktualisiert: "Feb 2024" },
      { name: "Wissenschaftliches Institut der AOK (WIdO)", url: "https://wido.de", aktualisiert: "Mär 2024" },
    ],
    evidenz: "gering" as EvidenzLevel,
    evidenzHinweis: "Grunddaten zur Versicherungsstruktur sind solide; Verhaltensänderungen, Versorgungseffekte und politische Umsetzungshürden machen die Gesamtwirkung hochgradig unsicher.",
  },
  beitragssatz: {
    titel: "Krankenversicherungs-Beitragssatz",
    beschreibung: "Allgemeiner Beitragssatz zur gesetzlichen Krankenversicherung (GKV). Arbeitgeber und Arbeitnehmer teilen ihn je zur Hälfte. Der Zusatzbeitrag der Kassen ist nicht eingeschlossen. Eine Erhöhung erhöht die Lohnnebenkosten und wirkt damit beschäftigungshemmend.",
    aktuellerWert: "14,6 % des Bruttolohns (je 7,3 % AG + AN)",
    berechnungslogik: "Pro +1 Prozentpunkt: ca. +4 Mrd. € Mehreinnahmen für GKV (GKV-Ausgabenvolumen ~310 Mrd. €, ~44 Mio. Pflichtversicherte). Persönliche Belastung: ca. +25 €/Monat je 0,1 Prozentpunkt (Ø-Bruttolohn ~3.800 €).",
    annahmen: ["~44 Mio. GKV-Pflichtversicherte", "Ø Bruttolohn 3.800 €/Monat", "Lineare Skalierung der Beitragseinnahmen", "Keine Verhaltensanpassung (Privatisierung) modelliert"],
    quellen: [
      { name: "Bundesministerium für Gesundheit – GKV-Finanzergebnisse", url: "https://bundesgesundheitsministerium.de", aktualisiert: "Jan 2024" },
      { name: "GKV-Spitzenverband", url: "https://gkv-spitzenverband.de", aktualisiert: "Mär 2024" },
    ],
    evidenz: "mittel" as EvidenzLevel,
    evidenzHinweis: "Fiskalischer Direkteffekt gut modellierbar; Beschäftigungs- und Verhaltenseffekte nicht enthalten.",
  },
  rentenniveau: {
    titel: "Rentenniveau (% des Durchschnittslohns)",
    beschreibung: "Das Rentenniveau beschreibt die Rente eines Durchschnittsverdieners nach 45 Beitragsjahren im Verhältnis zum aktuellen Durchschnittslohn (Standardrente). Derzeit liegt es bei 48 %. Ein sinkender Wert führt zu Altersarmut, ein steigender erhöht die Rentenausgaben erheblich.",
    aktuellerWert: "48 % des Durchschnittslohns (Haltelinie bis 2025)",
    berechnungslogik: "Pro +1 Prozentpunkt Niveau: ca. +4 Mrd. € Mehrausgaben p.a. (27 Mio. Rentner × Ø-Anpassung). Persönliche Wirkung: ±8 €/Monat je Prozentpunkt für einen Durchschnittsrentner.",
    annahmen: ["~27 Mio. Rentenempfänger", "Lineare Skalierung der Ausgaben", "Keine Auswirkung auf Beitragseinnahmen modelliert", "Haltelinie 48 % als Baseline (bis 2025 gesetzlich)"],
    quellen: [
      { name: "Deutsche Rentenversicherung – Rentenatlas", url: "https://drv-bund.de", aktualisiert: "Mär 2024" },
      { name: "Bundesministerium für Arbeit und Soziales", url: "https://bmas.de", aktualisiert: "Jan 2024" },
    ],
    evidenz: "mittel" as EvidenzLevel,
    evidenzHinweis: "Ausgabeneffekt gut modellierbar; Verhaltensanpassungen der Beitragszahler und Altersarmuts-Folgekosten nicht einbezogen.",
  },
  unternehmenssteuer: {
    titel: "Unternehmenssteuer (kombinierter Satz)",
    beschreibung: "Kombinierter Satz aus Körperschaftsteuer (15 %) und durchschnittlicher Gewerbesteuer (~14,9 %). Beeinflusst die Standortattraktivität, Investitionsbereitschaft und Steuervermeidungsanreize. Deutschland liegt im oberen OECD-Drittel.",
    aktuellerWert: "~29,9 % kombinierter Effektivsatz (KSt 15 % + GewSt ~14,9 %)",
    berechnungslogik: "Pro +1 Prozentpunkt: ca. +3 Mrd. € Steuereinnahmen (linearer Schätzwert). Wachstumseffekt: −0,015 % BIP je +1 pp (OECD-Metaanalyse: Unternehmenssteuer ist die wachstumsschädlichste Steuerart). Investitionshemmnis: −0,3 % Nettoinvestitionsquote je +1 pp.",
    annahmen: ["Lineare Skalierung der Steuereinnahmen", "OECD-Wachstumsmultiplikator −0,015 %/pp", "Keine Modellierung von Steuervermeidung oder Unternehmensabwanderung"],
    quellen: [
      { name: "Bundesministerium der Finanzen – Unternehmensbesteuerung", url: "https://bundesfinanzministerium.de", aktualisiert: "Feb 2024" },
      { name: "OECD Tax Database", url: "https://oecd.org", aktualisiert: "Jan 2024" },
    ],
    evidenz: "mittel" as EvidenzLevel,
    evidenzHinweis: "Steuereinnahmeneffekt modellierbar; Verhaltensanpassungen (Verlagerung, Vermeidung) haben große Unsicherheit.",
  },
  erbschaftssteuer: {
    titel: "Erbschaft-Freibetrag (Kinder)",
    beschreibung: "Persönlicher Freibetrag für Erbschaften von Kindern. Derzeit 400.000 € alle 10 Jahre. Alles oberhalb wird mit 7–30 % besteuert (Steuerklasse I). Eine Absenkung erhöht das Steueraufkommen, trifft aber auch selbstgenutztes Wohneigentum. Eine Erhöhung schont Erben, mindert jedoch Einnahmen.",
    aktuellerWert: "400.000 € Freibetrag (Steuerklasse I, Kinder, alle 10 J.)",
    berechnungslogik: "Pro −100.000 € Freibetrag (Absenkung): ca. +0,5 Mrd. € Steuermehreinnahmen. Gesamtaufkommen 2023: ~10,5 Mrd. €. Effekt stark abhängig von Immobilienpreisen und Vermögenskonzentration.",
    annahmen: ["Erbschaftssteueraufkommen 2023: ~10,5 Mrd. €", "Linearer Schätzwert: 0,5 Mrd. je 100k € Freibetragssenkung", "Keine Modellierung von Schenkungen zur Steueroptimierung"],
    quellen: [
      { name: "Statistisches Bundesamt – Erbschaft- und Schenkungsteuer", url: "https://destatis.de", aktualisiert: "Feb 2024" },
      { name: "Bundesministerium der Finanzen", url: "https://bundesfinanzministerium.de", aktualisiert: "Jan 2024" },
    ],
    evidenz: "mittel" as EvidenzLevel,
    evidenzHinweis: "Aufkommenseffekte schwer zu schätzen wegen starker Abhängigkeit von Immobilienmarkt und Vermögensverteilung.",
  },
};

export const scenarioMultipliers: Record<ScenarioMode, number> = {
  optimistisch: 1.3,
  realistisch: 1.0,
  pessimistisch: 0.65,
};

export const partyProfiles = [
  { name: "CDU/CSU", farbe: "#1d3a6e", abk: "CDU", beamte: 4700, ministerien: 14, verteidigung: 2.5, fachkraefte: 250, buergergeld: 450, rentenalter: 68, einkommensteuer: 40, vermoegenssteuer: false },
  { name: "SPD",     farbe: "#c0392b", abk: "SPD", beamte: 5000, ministerien: 17, verteidigung: 2.0, fachkraefte: 300, buergergeld: 560, rentenalter: 67, einkommensteuer: 45, vermoegenssteuer: false },
  { name: "FDP",     farbe: "#f0c040", abk: "FDP", beamte: 4200, ministerien: 12, verteidigung: 2.0, fachkraefte: 400, buergergeld: 420, rentenalter: 69, einkommensteuer: 35, vermoegenssteuer: false },
  { name: "Grüne",   farbe: "#2ecc71", abk: "GRÜ", beamte: 5200, ministerien: 18, verteidigung: 1.5, fachkraefte: 350, buergergeld: 620, rentenalter: 67, einkommensteuer: 48, vermoegenssteuer: true },
  { name: "AfD",     farbe: "#16a085", abk: "AfD", beamte: 4000, ministerien: 12, verteidigung: 3.0, fachkraefte: 80,  buergergeld: 400, rentenalter: 65, einkommensteuer: 38, vermoegenssteuer: false },
  { name: "Linke",   farbe: "#8e44ad", abk: "LNK", beamte: 5800, ministerien: 20, verteidigung: 1.0, fachkraefte: 200, buergergeld: 700, rentenalter: 63, einkommensteuer: 53, vermoegenssteuer: true },
];

export const barData = [
  { name: "Soziales", einnahmen: 0, ausgaben: 175 },
  { name: "Verteidigung", einnahmen: 0, ausgaben: 52 },
  { name: "Bildung", einnahmen: 0, ausgaben: 21 },
  { name: "Zinsen", einnahmen: 0, ausgaben: 37 },
  { name: "Sonstiges", einnahmen: 460, ausgaben: 191 },
];

export const lineData = [
  { year: "2024", statusQuo: 0.2, simulation: 0.2 },
  { year: "2025", statusQuo: 0.5, simulation: 0.9 },
  { year: "2026", statusQuo: 0.8, simulation: 1.3 },
  { year: "2027", statusQuo: 1.0, simulation: 1.6 },
  { year: "2028", statusQuo: 1.1, simulation: 1.9 },
  { year: "2029", statusQuo: 1.2, simulation: 2.2 },
  { year: "2030", statusQuo: 1.2, simulation: 2.5 },
];

export const areaData = [
  { year: "2020", einnahmen: 750, ausgaben: 850 },
  { year: "2021", einnahmen: 780, ausgaben: 860 },
  { year: "2022", einnahmen: 820, ausgaben: 840 },
  { year: "2023", einnahmen: 890, ausgaben: 910 },
  { year: "2024", einnahmen: 948, ausgaben: 950 },
  { year: "2025", einnahmen: 930, ausgaben: 960 },
  { year: "2026", einnahmen: 950, ausgaben: 980 },
  { year: "2027", einnahmen: 970, ausgaben: 990 },
  { year: "2028", einnahmen: 990, ausgaben: 1010 },
  { year: "2029", einnahmen: 1010, ausgaben: 1030 },
  { year: "2030", einnahmen: 1040, ausgaben: 1060 },
];

export const pieData = [
  { name: "Arbeit & Soziales", value: 175 },
  { name: "Verteidigung", value: 52 },
  { name: "Bildung & Forschung", value: 21 },
  { name: "Verkehr", value: 38 },
  { name: "Zinsen", value: 37 },
  { name: "Sonstiges", value: 153.8 },
];
export const COLORS = ["#00c8b4", "#4caf82", "#f5a623", "#8faabb", "#e05c5c", "#243447"];

export const ageData = [
  { age: "0-14", male: -6.5, female: 6.2 },
  { age: "15-24", male: -4.3, female: 4.1 },
  { age: "25-44", male: -11.4, female: 11.1 },
  { age: "45-59", male: -10.2, female: 10.0 },
  { age: "60-74", male: -7.8, female: 8.5 },
  { age: "75+", male: -3.9, female: 5.6 },
];

export const kpis: KPIMeta[] = [
  { label: "Haushaltsdefizit",    value: "-34.2 Mrd.",  color: "#e05c5c", sparkPoints: "0,10 10,12 20,5 30,15 40,8 50,18",  sparkColor: "#e05c5c", source: "Bundesministerium der Finanzen",     updated: "Mär 2024", confidence: "hoch"   },
  { label: "Staatsverschuldung",  value: "2.445 Mrd.",  color: "#f0f4f8", sparkPoints: "0,15 10,14 20,12 30,10 40,8 50,6",   sparkColor: "#8faabb", source: "Deutsche Bundesbank",             updated: "Feb 2024", confidence: "hoch"   },
  { label: "Steueraufkommen",     value: "948 Mrd.",    color: "#4caf82", sparkPoints: "0,15 10,12 20,16 30,8 40,5 50,2",    sparkColor: "#4caf82", source: "Statistisches Bundesamt",         updated: "Jan 2024", confidence: "hoch"   },
  { label: "Gesundheitskosten",   value: "468 Mrd.",    color: "#f0f4f8", sparkPoints: "0,12 10,11 20,13 30,10 40,9 50,11",  sparkColor: "#8faabb", source: "Bundesministerium für Gesundheit", updated: "Feb 2024", confidence: "mittel" },
  { label: "Rentenkosten",        value: "362 Mrd.",    color: "#f0f4f8", sparkPoints: "0,15 10,13 20,11 30,10 40,9 50,8",   sparkColor: "#8faabb", source: "Deutsche Rentenversicherung",     updated: "Jan 2024", confidence: "hoch"   },
  { label: "Arbeitslosenquote",   value: "5.7%",        color: "#e05c5c", sparkPoints: "0,5 10,8 20,6 30,10 40,12 50,14",    sparkColor: "#e05c5c", source: "Bundesagentur für Arbeit",         updated: "Mär 2024", confidence: "hoch"   },
  { label: "Fachkräftemangel",    value: "890k",        color: "#f5a623", sparkPoints: "0,5 10,6 20,8 30,10 40,12 50,14",    sparkColor: "#f5a623", source: "IW Köln / BA",                    updated: "Feb 2024", confidence: "mittel" },
  { label: "Wirtschaftswachstum", value: "+0.8%",       color: "#4caf82", sparkPoints: "0,15 10,12 20,10 30,7 40,4 50,2",    sparkColor: "#4caf82", source: "Sachverständigenrat Wirtschaft",   updated: "Nov 2023", confidence: "mittel" },
];
