// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/modus-wechsel/EinfacherModus.tsx": () => import("../components/mockups/modus-wechsel/EinfacherModus.tsx"),
  "./components/mockups/modus-wechsel/ErweiterterModusToggle.tsx": () => import("../components/mockups/modus-wechsel/ErweiterterModusToggle.tsx"),
  "./components/mockups/diz/AIAnalysis.tsx": () => import("../components/mockups/diz/AIAnalysis.tsx"),
  "./components/mockups/diz/Comparison.tsx": () => import("../components/mockups/diz/Comparison.tsx"),
  "./components/mockups/diz/Dashboard.tsx": () => import("../components/mockups/diz/Dashboard.tsx"),
  "./components/mockups/diz/LandingPage.tsx": () => import("../components/mockups/diz/LandingPage.tsx"),
  "./components/mockups/diz/MobileDashboard.tsx": () => import("../components/mockups/diz/MobileDashboard.tsx"),
  "./components/mockups/diz/MobileLanding.tsx": () => import("../components/mockups/diz/MobileLanding.tsx"),
  "./components/mockups/diz/MobileSimulator.tsx": () => import("../components/mockups/diz/MobileSimulator.tsx"),
  "./components/mockups/diz/Simulator.tsx": () => import("../components/mockups/diz/Simulator.tsx")
};
